spring.application.name=fibank-cash-desk



#Data
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.h2.console.enabled=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always


logger.com.ratimid.fibank_cash_desk=INFO
logger.ratimid.fibank_cash_desk.services=DEBUG
logger.ratimid.fibank_cash_desk.controllers=DEBUG
