--INSERT API_KEY
INSERT INTO API_KEY (ID, HASHED_KEY, CLIENT, ACTIVE) VALUES (NEXT VALUE FOR api_key_seq, '$2a$12$GFZzyY5Erg5nYQKC/ae1quXIyX236x0Sa4D3Wg32.Zgwiuy79oe0K', 'FIB_CLIENT', true);

--INSERT CASHIER
INSERT INTO CASHIER (ID, FIRST_NAME, LAST_NAME) VALUES (NEXT VALUE FOR cashier_seq, 'Martina', 'Georgieva');
INSERT INTO CASHIER (ID, FIRST_NAME, LAST_NAME) VALUES (NEXT VALUE FOR cashier_seq, 'Peter', 'Ivanov');
INSERT INTO CASHIER (ID, FIRST_NAME, LAST_NAME) VALUES (NEXT VALUE FOR cashier_seq, 'Linda', 'Kostadinova');

--INSERT CURRENCY
INSERT INTO CURRENCY (ID, CURRENCY_CODE, NAME) VALUES (NEXT VALUE FOR currency_seq, 'BGN', 'Лев');
INSERT INTO CURRENCY (ID, CURRENCY_CODE, NAME) VALUES (NEXT VALUE FOR currency_seq, 'EUR', 'Евро');

--INSERT DENOMINATION
INSERT INTO DENOMINATION (ID, NOMINAL_VALUE, CURRENCY_ID)
VALUES (NEXT VALUE FOR denomination_seq, 1, (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN'));
INSERT INTO DENOMINATION (ID, NOMINAL_VALUE, CURRENCY_ID)
VALUES (NEXT VALUE FOR denomination_seq, 2, (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN'));
INSERT INTO DENOMINATION (ID, NOMINAL_VALUE, CURRENCY_ID)
VALUES (NEXT VALUE FOR denomination_seq, 5, (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN'));
INSERT INTO DENOMINATION (ID, NOMINAL_VALUE, CURRENCY_ID)
VALUES (NEXT VALUE FOR denomination_seq, 10, (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN'));
INSERT INTO DENOMINATION (ID, NOMINAL_VALUE, CURRENCY_ID)
VALUES (NEXT VALUE FOR denomination_seq, 20, (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN'));
INSERT INTO DENOMINATION (ID, NOMINAL_VALUE, CURRENCY_ID)
VALUES (NEXT VALUE FOR denomination_seq, 50, (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN'));
INSERT INTO DENOMINATION (ID, NOMINAL_VALUE, CURRENCY_ID)
VALUES (NEXT VALUE FOR denomination_seq, 100, (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN'));
INSERT INTO DENOMINATION (ID, NOMINAL_VALUE, CURRENCY_ID)
VALUES (NEXT VALUE FOR denomination_seq, 1, (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR'));
INSERT INTO DENOMINATION (ID, NOMINAL_VALUE, CURRENCY_ID)
VALUES (NEXT VALUE FOR denomination_seq, 2, (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR'));
INSERT INTO DENOMINATION (ID, NOMINAL_VALUE, CURRENCY_ID)
VALUES (NEXT VALUE FOR denomination_seq, 5, (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR'));
INSERT INTO DENOMINATION (ID, NOMINAL_VALUE, CURRENCY_ID)
VALUES (NEXT VALUE FOR denomination_seq, 10, (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR'));
INSERT INTO DENOMINATION (ID, NOMINAL_VALUE, CURRENCY_ID)
VALUES (NEXT VALUE FOR denomination_seq, 20, (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR'));
INSERT INTO DENOMINATION (ID, NOMINAL_VALUE, CURRENCY_ID)
VALUES (NEXT VALUE FOR denomination_seq, 50, (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR'));
INSERT INTO DENOMINATION (ID, NOMINAL_VALUE, CURRENCY_ID)
VALUES (NEXT VALUE FOR denomination_seq, 100, (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR'));


--INSERT BALANCE
INSERT INTO BALANCE (ID, AMOUNT, CASHIER_ID, CURRENCY_ID)
VALUES (NEXT VALUE FOR balance_seq, 1000,(SELECT ID FROM CASHIER WHERE FIRST_NAME = 'Martina'), (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN'));
INSERT INTO BALANCE (ID, AMOUNT, CASHIER_ID, CURRENCY_ID)
VALUES (NEXT VALUE FOR balance_seq, 1000,(SELECT ID FROM CASHIER WHERE FIRST_NAME = 'Peter'), (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN'));
INSERT INTO BALANCE (ID, AMOUNT, CASHIER_ID, CURRENCY_ID)
VALUES (NEXT VALUE FOR balance_seq, 1000,(SELECT ID FROM CASHIER WHERE FIRST_NAME = 'Linda'), (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN'));
INSERT INTO BALANCE (ID, AMOUNT, CASHIER_ID, CURRENCY_ID)
VALUES (NEXT VALUE FOR balance_seq, 2000,(SELECT ID FROM CASHIER WHERE FIRST_NAME = 'Martina'), (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR'));
INSERT INTO BALANCE (ID, AMOUNT, CASHIER_ID, CURRENCY_ID)
VALUES (NEXT VALUE FOR balance_seq, 2000,(SELECT ID FROM CASHIER WHERE FIRST_NAME = 'Peter'), (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR'));
INSERT INTO BALANCE (ID, AMOUNT, CASHIER_ID, CURRENCY_ID)
VALUES (NEXT VALUE FOR balance_seq, 2000,(SELECT ID FROM CASHIER WHERE FIRST_NAME = 'Linda'), (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR'));

--INSERT BALANCE INVENTORY
INSERT INTO BALANCE_INVENTORY (ID, BALANCE_ID, DENOMINATION_ID, QUANTITY)
VALUES (NEXT VALUE FOR balance_inventory_seq, (SELECT ID FROM BALANCE WHERE CASHIER_ID = (SELECT ID FROM CASHIER WHERE FIRST_NAME = 'Martina') AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN')), (SELECT ID FROM DENOMINATION WHERE NOMINAL_VALUE = 10 AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN')), 50);
INSERT INTO BALANCE_INVENTORY (ID, BALANCE_ID, DENOMINATION_ID, QUANTITY)
VALUES (NEXT VALUE FOR balance_inventory_seq, (SELECT ID FROM BALANCE WHERE CASHIER_ID = (SELECT ID FROM CASHIER WHERE FIRST_NAME = 'Peter') AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN')), (SELECT ID FROM DENOMINATION WHERE NOMINAL_VALUE = 10 AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN')), 50);
INSERT INTO BALANCE_INVENTORY (ID, BALANCE_ID, DENOMINATION_ID, QUANTITY)
VALUES (NEXT VALUE FOR balance_inventory_seq, (SELECT ID FROM BALANCE WHERE CASHIER_ID = (SELECT ID FROM CASHIER WHERE FIRST_NAME = 'Linda') AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN')), (SELECT ID FROM DENOMINATION WHERE NOMINAL_VALUE = 10 AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN')), 50);
INSERT INTO BALANCE_INVENTORY (ID, BALANCE_ID, DENOMINATION_ID, QUANTITY)
VALUES (NEXT VALUE FOR balance_inventory_seq, (SELECT ID FROM BALANCE WHERE CASHIER_ID = (SELECT ID FROM CASHIER WHERE FIRST_NAME = 'Martina') AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN')), (SELECT ID FROM DENOMINATION WHERE NOMINAL_VALUE = 50 AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN')), 10);
INSERT INTO BALANCE_INVENTORY (ID, BALANCE_ID, DENOMINATION_ID, QUANTITY)
VALUES (NEXT VALUE FOR balance_inventory_seq, (SELECT ID FROM BALANCE WHERE CASHIER_ID = (SELECT ID FROM CASHIER WHERE FIRST_NAME = 'Peter') AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN')), (SELECT ID FROM DENOMINATION WHERE NOMINAL_VALUE = 50 AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN')), 10);
INSERT INTO BALANCE_INVENTORY (ID, BALANCE_ID, DENOMINATION_ID, QUANTITY)
VALUES (NEXT VALUE FOR balance_inventory_seq, (SELECT ID FROM BALANCE WHERE CASHIER_ID = (SELECT ID FROM CASHIER WHERE FIRST_NAME = 'Linda') AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN')), (SELECT ID FROM DENOMINATION WHERE NOMINAL_VALUE = 50 AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'BGN')), 10);
INSERT INTO BALANCE_INVENTORY (ID, BALANCE_ID, DENOMINATION_ID, QUANTITY)
VALUES (NEXT VALUE FOR balance_inventory_seq, (SELECT ID FROM BALANCE WHERE CASHIER_ID = (SELECT ID FROM CASHIER WHERE FIRST_NAME = 'Martina') AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR')), (SELECT ID FROM DENOMINATION WHERE NOMINAL_VALUE = 10 AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR')), 100);
INSERT INTO BALANCE_INVENTORY (ID, BALANCE_ID, DENOMINATION_ID, QUANTITY)
VALUES (NEXT VALUE FOR balance_inventory_seq, (SELECT ID FROM BALANCE WHERE CASHIER_ID = (SELECT ID FROM CASHIER WHERE FIRST_NAME = 'Peter') AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR')), (SELECT ID FROM DENOMINATION WHERE NOMINAL_VALUE = 10 AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR')), 100);
INSERT INTO BALANCE_INVENTORY (ID, BALANCE_ID, DENOMINATION_ID, QUANTITY)
VALUES (NEXT VALUE FOR balance_inventory_seq, (SELECT ID FROM BALANCE WHERE CASHIER_ID = (SELECT ID FROM CASHIER WHERE FIRST_NAME = 'Linda') AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR')), (SELECT ID FROM DENOMINATION WHERE NOMINAL_VALUE = 10 AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR')), 100);
INSERT INTO BALANCE_INVENTORY (ID, BALANCE_ID, DENOMINATION_ID, QUANTITY)
VALUES (NEXT VALUE FOR balance_inventory_seq, (SELECT ID FROM BALANCE WHERE CASHIER_ID = (SELECT ID FROM CASHIER WHERE FIRST_NAME = 'Martina') AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR')), (SELECT ID FROM DENOMINATION WHERE NOMINAL_VALUE = 20 AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR')), 20);
INSERT INTO BALANCE_INVENTORY (ID, BALANCE_ID, DENOMINATION_ID, QUANTITY)
VALUES (NEXT VALUE FOR balance_inventory_seq, (SELECT ID FROM BALANCE WHERE CASHIER_ID = (SELECT ID FROM CASHIER WHERE FIRST_NAME = 'Peter') AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR')), (SELECT ID FROM DENOMINATION WHERE NOMINAL_VALUE = 20 AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR')), 20);
INSERT INTO BALANCE_INVENTORY (ID, BALANCE_ID, DENOMINATION_ID, QUANTITY)
VALUES (NEXT VALUE FOR balance_inventory_seq, (SELECT ID FROM BALANCE WHERE CASHIER_ID = (SELECT ID FROM CASHIER WHERE FIRST_NAME = 'Linda') AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR')), (SELECT ID FROM DENOMINATION WHERE NOMINAL_VALUE = 20 AND CURRENCY_ID = (SELECT ID FROM CURRENCY WHERE CURRENCY_CODE = 'EUR')), 20);

